### ISSUE TITLE
Comparatively high initial prediction time for first predict() hit

### ISSUE THREAD

**Issue by nemeer** [Pandora-Intelligence/crosslingual-coreference#15]
I am using minilm model with language 'en_core_web_sm'.
While comparing the prediction time, i.e., _**predictor.predict(text)**_, the prediction time for first hit is always a bit high than the following hits.
Suppose after creating a predictor object, I call predict as follows:

`predictor.predict(text)` ---> first call
`predictor.predict(text)` ---> second call
`predictor.predict(text)` ---> third call

Time taken for the first call is comparatively a bit higher(.2 sec) than the next prediction calls(.05 sec).
Could you please help me understand why this **initial hit takes a bit high prediction time**?

**Comment by davidberenstein1957** [comment]
@nemeer this is a PyTorch and probably general NN design choice, which is caused by the first call setting up a lot of things within the network like cache, memory on the GPU, graph optimization.

https://datascience.stackexchange.com/questions/63476/why-the-first-prediction-of-neural-network-in-pytorch-is-slower-than-following-p

**Comment by nemeer** [comment]
Thanks for clarifying @davidberenstein1957.
